export type ConsulateType = "embassy" | "general" | "honorary";

export type TurkishMission = {
  id: string;
  name: string;
  type: ConsulateType;
  city: string;
  address: string;
  postalCode: string;
  phone: string;
  emergencyPhone?: string;
  fax?: string;
  email?: string;
  website?: string;
  jurisdiction: string;
  hours?: string;
};

/** Kaynak: Auswärtiges Amt / mfa.gov.tr (2025–2026) */
export const CONSULAR_CALL_CENTER = {
  label: "Konsolosluk Çağrı Merkezi (7/24)",
  phone: "+49 30 5683 73099",
};

export const TURKISH_MISSIONS_GERMANY: TurkishMission[] = [
  {
    id: "berlin-embassy",
    name: "Berlin Büyükelçiliği",
    type: "embassy",
    city: "Berlin",
    address: "Tiergartenstraße 19–21",
    postalCode: "10785",
    phone: "+49 30 275850",
    fax: "+49 30 27590915",
    email: "berlin.be@mfa.gov.tr",
    website: "https://berlin-emb.mfa.gov.tr",
    jurisdiction: "Almanya (Bundesgebiet — diplomatik temsil)",
    hours: "Pzt–Cum 08:45–12:45, 13:45–17:45",
  },
  {
    id: "berlin-cg",
    name: "Berlin Başkonsolosluğu",
    type: "general",
    city: "Berlin",
    address: "Heerstraße 21",
    postalCode: "14052",
    phone: "+49 30 89680211",
    emergencyPhone: "+49 163 9519346",
    fax: "+49 30 8931898",
    email: "konsulat.berlin@mfa.gov.tr",
    website: "https://berlin-cg.mfa.gov.tr",
    jurisdiction: "Berlin, Brandenburg, Mecklenburg-Vorpommern, Sachsen",
    hours: "Pzt–Cum 09:00–13:00",
  },
  {
    id: "duesseldorf",
    name: "Düsseldorf Başkonsolosluğu",
    type: "general",
    city: "Düsseldorf",
    address: "Willstätterstraße 9",
    postalCode: "40549",
    phone: "+49 211 454780",
    fax: "+49 211 4547822",
    email: "konsulat.duesseldorf@mfa.gov.tr",
    website: "https://duesseldorf-cg.mfa.gov.tr",
    jurisdiction: "NRW — Düsseldorf bölgesi (Essen ve Mülheim hariç)",
    hours: "Pzt–Cum 08:30–12:30",
  },
  {
    id: "essen",
    name: "Essen Başkonsolosluğu",
    type: "general",
    city: "Essen",
    address: "Zehnthof 55",
    postalCode: "45127",
    phone: "+49 201 842160",
    fax: "+49 201 423867",
    email: "konsulat.essen@mfa.gov.tr",
    website: "https://essen-cg.mfa.gov.tr",
    jurisdiction: "NRW — Arnsberg bölgesi; Düsseldorf bölgesinden Essen ve Mülheim",
    hours: "Pzt–Cum 08:30–11:30",
  },
  {
    id: "frankfurt",
    name: "Frankfurt Başkonsolosluğu",
    type: "general",
    city: "Frankfurt am Main",
    address: "Kennedyallee 115–117",
    postalCode: "60596",
    phone: "+49 69 713773",
    emergencyPhone: "+49 160 96652270",
    fax: "+49 69 709032",
    email: "konsulat.frankfurt@mfa.gov.tr",
    website: "https://frankfurt-cg.mfa.gov.tr",
    jurisdiction: "Hessen eyaleti",
    hours: "Pzt–Cum 09:00–13:00, 13:30–14:30",
  },
  {
    id: "hamburg",
    name: "Hamburg Başkonsolosluğu",
    type: "general",
    city: "Hamburg",
    address: "Tesdorpfstraße 18",
    postalCode: "20148",
    phone: "+49 40 4480330",
    fax: "+49 40 445258",
    email: "konsulat.hamburg@mfa.gov.tr",
    website: "https://hamburg-cg.mfa.gov.tr",
    jurisdiction: "Hamburg, Schleswig-Holstein",
    hours: "Pzt–Cum 08:30–12:00",
  },
  {
    id: "hannover",
    name: "Hannover Başkonsolosluğu",
    type: "general",
    city: "Hannover",
    address: "An der Christuskirche 3",
    postalCode: "30167",
    phone: "+49 511 768650",
    fax: "+49 511 17700",
    email: "konsulat.hannover@mfa.gov.tr",
    website: "https://hannover-cg.mfa.gov.tr",
    jurisdiction: "Niedersachsen, Bremen, Sachsen-Anhalt",
    hours: "Pzt–Cum 08:30–12:00",
  },
  {
    id: "koeln",
    name: "Köln Başkonsolosluğu (Hürth)",
    type: "general",
    city: "Hürth",
    address: "Luxemburger Straße 285 (Köln Straße girişi)",
    postalCode: "50354",
    phone: "+49 2233 93980",
    emergencyPhone: "+49 163 9519306",
    fax: "+49 2233 9398166",
    email: "konsulat.koeln@mfa.gov.tr",
    website: "https://cologne-cg.mfa.gov.tr",
    jurisdiction: "NRW — Köln bölgesi (Aachen, Bonn, Köln, Leverkusen vb.)",
    hours: "Pzt–Cum 08:30–12:30, 13:00–16:00",
  },
  {
    id: "kassel",
    name: "Kassel Başkonsolosluğu",
    type: "general",
    city: "Kassel",
    address: "Schützenstraße 29",
    postalCode: "34125",
    phone: "+49 30 30807090",
    emergencyPhone: "+49 163 7789670",
    email: "konsulat.kassel@mfa.gov.tr",
    website: "https://kassel-bk.mfa.gov.tr",
    jurisdiction: "Hessen (Kassel bölgesi), Thüringen, kısmi Niedersachsen ve NRW",
    hours: "Pzt–Cum 09:00–12:00, 13:00–16:00",
  },
  {
    id: "karlsruhe",
    name: "Karlsruhe Başkonsolosluğu",
    type: "general",
    city: "Karlsruhe",
    address: "Rintheimer Straße 82",
    postalCode: "76131",
    phone: "+49 721 984400",
    fax: "+49 721 856013",
    email: "konsulat.karlsruhe@mfa.gov.tr",
    website: "https://karlsruhe-cg.mfa.gov.tr",
    jurisdiction: "Baden-Württemberg — Karlsruhe ve Freiburg bölgeleri",
    hours: "Pzt–Cum 08:30–11:30",
  },
  {
    id: "mainz",
    name: "Mainz Başkonsolosluğu",
    type: "general",
    city: "Mainz",
    address: "An der Karlsschanze 7",
    postalCode: "55116",
    phone: "+49 6131 982600",
    fax: "+49 6131 835119",
    email: "konsulat.mainz@mfa.gov.tr",
    website: "https://mainz-cg.mfa.gov.tr",
    jurisdiction: "Rheinland-Pfalz, Saarland",
    hours: "Pzt–Cum 08:30–11:30",
  },
  {
    id: "muenchen",
    name: "Münih Başkonsolosluğu",
    type: "general",
    city: "München",
    address: "Menzinger Straße 3",
    postalCode: "80638",
    phone: "+49 89 1780310",
    fax: "+49 89 1785660",
    email: "konsulat.muenchen@mfa.gov.tr",
    website: "https://muenchen-cg.mfa.gov.tr",
    jurisdiction: "Bayern — Niederbayern, Oberbayern, Schwaben",
    hours: "Pzt–Cum 08:30–11:00",
  },
  {
    id: "muenster",
    name: "Münster Başkonsolosluğu",
    type: "general",
    city: "Münster",
    address: "Lotharinger Straße 25–27",
    postalCode: "48147",
    phone: "+49 251 414700",
    fax: "+49 251 43327",
    email: "konsulat.muenster@mfa.gov.tr",
    website: "https://muenster-cg.mfa.gov.tr",
    jurisdiction: "NRW — Münster ve Detmold bölgeleri",
    hours: "Pzt–Cum 08:30–12:30",
  },
  {
    id: "nuernberg",
    name: "Nürnberg Başkonsolosluğu",
    type: "general",
    city: "Nürnberg",
    address: "Regensburger Straße 69",
    postalCode: "90478",
    phone: "+49 911 946760",
    fax: "+49 911 468962",
    email: "konsulat.nuernberg@mfa.gov.tr",
    website: "https://nuernberg-cg.mfa.gov.tr",
    jurisdiction: "Bayern — Franken ve Oberpfalz bölgeleri",
    hours: "Pzt–Cum 08:30–16:30",
  },
  {
    id: "stuttgart",
    name: "Stuttgart Başkonsolosluğu",
    type: "general",
    city: "Stuttgart",
    address: "Kerner Platz 7",
    postalCode: "70182",
    phone: "+49 711 166670",
    fax: "+49 711 2622102",
    email: "konsulat.stuttgart@mfa.gov.tr",
    website: "https://stuttgart-cg.mfa.gov.tr",
    jurisdiction: "Baden-Württemberg — Stuttgart ve Tübingen bölgeleri",
    hours: "Pzt–Cum 08:30–12:30",
  },
  {
    id: "aachen",
    name: "Aachen Fahri Konsolosluğu",
    type: "honorary",
    city: "Aachen",
    address: "Aachen (randevu ile)",
    postalCode: "",
    phone: "+49 241 90053201",
    fax: "+49 241 90053202",
    jurisdiction: "NRW — Aachen, Düren, Heinsberg ilçeleri",
    hours: "Pzt–Per 10:00–13:00 (randevu ile)",
  },
  {
    id: "regensburg",
    name: "Regensburg Fahri Konsolosluğu",
    type: "honorary",
    city: "Regensburg",
    address: "Dechbettener Straße 10",
    postalCode: "93049",
    phone: "+49 941 78036620",
    fax: "+49 941 57770",
    jurisdiction: "Bayern — Oberfranken ve Oberpfalz",
    hours: "Pzt–Per 08:00–17:30, Cum 08:00–14:00",
  },
];

export const MISSION_TYPE_LABELS: Record<ConsulateType, string> = {
  embassy: "Büyükelçilik",
  general: "Başkonsolosluk",
  honorary: "Fahri konsolosluk",
};

export function mapsUrl(mission: TurkishMission) {
  const parts = [mission.address, mission.postalCode, mission.city, "Deutschland"].filter(Boolean);
  const q = encodeURIComponent(parts.join(", "));
  return `https://www.google.com/maps/search/?api=1&query=${q}`;
}

export function telUrl(phone: string) {
  return `tel:${phone.replace(/\s/g, "")}`;
}
